// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyBYhflzE1PcjzWrDNb9XxMz_eaOhZAx0',
    appId: '1:382586331965:web:cd61767ae31976a7f3db54',
    messagingSenderId: '382586331965',
    projectId: 'basic-7712b',
    authDomain: 'basic-7712b.firebaseapp.com',
    storageBucket: 'basic-7712b.firebasestorage.app',
    measurementId: 'G-2K1E6V1BE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzPgR1ruUaiufSPYgliWkbvCl8e4thcic',
    appId: '1:382586331965:android:86688cb84b14d09ff3db54',
    messagingSenderId: '382586331965',
    projectId: 'basic-7712b',
    storageBucket: 'basic-7712b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvHpxnBD1AMDzLSqBFQoCgpPtp20U0Adc',
    appId: '1:382586331965:ios:d830c167fdc1c608f3db54',
    messagingSenderId: '382586331965',
    projectId: 'basic-7712b',
    storageBucket: 'basic-7712b.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvHpxnBD1AMDzLSqBFQoCgpPtp20U0Adc',
    appId: '1:382586331965:ios:d830c167fdc1c608f3db54',
    messagingSenderId: '382586331965',
    projectId: 'basic-7712b',
    storageBucket: 'basic-7712b.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyBYhflzE1PcjzWrDNb9XxMz_eaOhZAx0',
    appId: '1:382586331965:web:204d6966723a0d05f3db54',
    messagingSenderId: '382586331965',
    projectId: 'basic-7712b',
    authDomain: 'basic-7712b.firebaseapp.com',
    storageBucket: 'basic-7712b.firebasestorage.app',
    measurementId: 'G-ZJQN1EWKYC',
  );
}
